import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <title>Seovileo</title>
                <link rel="icon" href="/favicon.ico" sizes="any" />
            </head>
            <body className={inter.className}>
                <div className="fixed top-0 left-0 bg-gradient-to-b from-black/20 to-white/0 w-full lg:h-[50vh] -z-50" />
                <Header />
                {children}
                <div className="h-[200vh]" />
            </body>
        </html>
    );
}
